# Generated by Django 4.1.7 on 2023-03-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CampusConnectApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                (
                    "roll",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("contact", models.CharField(max_length=20)),
                ("dept", models.CharField(max_length=10)),
                ("batch", models.IntegerField()),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
