# Generated by Django 4.1.7 on 2023-03-30 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CampusConnectApp", "0002_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sell",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                ("price", models.FloatField()),
                ("sold", models.BooleanField()),
                (
                    "roll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CampusConnectApp.users",
                    ),
                ),
            ],
        ),
    ]
