# Generated by Django 4.1.7 on 2023-03-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CampusConnectApp", "0005_alter_sell_sold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/lost")),
                ("description", models.TextField(max_length=500)),
                (
                    "roll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CampusConnectApp.users",
                    ),
                ),
            ],
        ),
    ]
