# Generated by Django 4.1.7 on 2023-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CampusConnectApp", "0010_restaurants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("Emergency", "Emergency"),
                    ("Administration", "Administration"),
                    ("Faculty", "Faculty"),
                ],
                max_length=50,
            ),
        ),
    ]
